name: Render R Quarto Document

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  render-document:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install packages
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
            packages:
               any::knitr
               any::rmarkdown
               any::jsonlite
               any::dplyr
               any::tidyverse
               any::readr
               any::lubridate
               any::forcats
               any::googledrive
               any::data.table
               any::quarto
               any::kableExtra

    - name: Render Document
      run: |
        Rscript -e 'quarto::render("ICU Status Report.qmd")'
