name: Render Quarto Document

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  render_quarto:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.0'

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v1
        with:
          packages: quarto

      - name: Render document
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: gfm
          path: ICU Status Report.qmd

      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Commit
        run: |
          git add .
          git commit -m "Updated report"
          git push origin main
