name: Render Report
on:
  schedule:
    - cron: '0 * * * *' # Run every hour
jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install R and dependencies
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: '4.3.0' # Set the version of R to use
          dependencies: |
            remotes::install_github("rstudio/quarto") # Install Quarto package
            remotes::install_github("rstudio/rmarkdown") # Install rmarkdown package
      - name: Render report
        run: Rscript -e 'rmarkdown::render("ICU Status Report.qmd", output_format = "quarto::quarto_html")'
