name: Render Report

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up R
      uses: r-lib/actions/setup-r@v1
      with:
        r-version: '4.1.0'
    - name: Install R packages
      run: |
        install.packages("rmarkdown")
        install.packages("knitr")
        install.packages("tinytex")
    - name: Render Report
      run: Rscript -e 'rmarkdown::render("path/to/report.Rq", output_format = "html_document")'
    - name: Commit and Push Changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Render report to HTML"
        commit_options: '--no-verify'
